import { Move } from './Move';

/**
 * Domain Events
 *
 * Events generated by the Game aggregate when state changes occur.
 * These drive the application layer's side effects (persistence, notifications, etc.)
 */

export type GameEventType =
  | 'GameStarted'
  | 'GameFinished'
  | 'GameReady'
  | 'MovePlayed'
  | 'PlayerJoined'
  | 'PlayerLeft'
  | 'PlayerBlocked'
  | 'PlayerReadyChanged'
  | 'TurnAdvanced';

export interface GameStartedPayload {
  gameId: number;
  firstPlayerId: number;
}

export interface GameFinishedPayload {
  gameId?: number;
  winnerId: number;
  reason: string;
  trappedPlayerId?: number | null;
}

export interface MovePlayedPayload {
  gameId?: number;
  playerId: number;
  move: Move;
  turnNumber: number;
}

export interface PlayerJoinedPayload {
  gameId: number;
  playerId: number;
}

export interface TurnAdvancedPayload {
  gameId: number;
  newCurrentPlayerId: number;
  phase: string;
}

export interface PlayerLeftPayload {
  gameId: number;
  userId: number;
}

export interface PlayerReadyChangedPayload {
  gameId: number;
  playerId: number;
  ready: boolean;
  readyStatuses: { playerId: number; ready: boolean }[];
}

export interface GameReadyPayload {
  gameId: number;
}

export type GameEventPayload =
  | GameStartedPayload
  | GameFinishedPayload
  | MovePlayedPayload
  | PlayerJoinedPayload
  | TurnAdvancedPayload
  | PlayerLeftPayload
  | PlayerReadyChangedPayload
  | GameReadyPayload;

export class GameEvent {
  public readonly occurredAt: Date;

  constructor(
    public readonly type: GameEventType,
    public readonly payload: GameEventPayload,
    public readonly aggregateId?: number
  ) {
    this.occurredAt = new Date();
  }
}

// Specific event classes for type safety
export class GameStartedEvent extends GameEvent {
  constructor(gameId: number, firstPlayerId: number) {
    super('GameStarted', { gameId, firstPlayerId }, gameId);
  }
}

export class GameFinishedEvent extends GameEvent {
  constructor(gameId: number, winnerId: number, reason: string) {
    super('GameFinished', { gameId, winnerId, reason }, gameId);
  }
}

export class MovePlayedEvent extends GameEvent {
  constructor(gameId: number, playerId: number, move: Move, turnNumber: number) {
    super('MovePlayed', { gameId, playerId, move, turnNumber }, gameId);
  }
}

export class PlayerJoinedEvent extends GameEvent {
  constructor(gameId: number, playerId: number) {
    super('PlayerJoined', { gameId, playerId }, gameId);
  }
}

export class TurnAdvancedEvent extends GameEvent {
  constructor(gameId: number, newCurrentPlayerId: number, phase: string) {
    super('TurnAdvanced', { gameId, newCurrentPlayerId, phase }, gameId);
  }
}

export class PlayerLeftEvent extends GameEvent {
  constructor(gameId: number, userId: number) {
    super('PlayerLeft', { gameId, userId }, gameId);
  }
}
